### ISSUE TITLE
Support int24 ?

### ISSUE THREAD

**Issue by sunng87** [clj-commons/gloss#2]
Hi ztallman, 

Is it possible to support int24 as a primitive? In Netty's ChannelBuffer, there is a getMedium and setMedium for 3-bytes integer. It's also found in many protocols such Diameter.

**Comment by cch1** [comment]
I'm looking for support for this feature.  Has it been added?  If not, are there any elegant work-arounds?

**Comment by ztellman** [comment]
It hasn't, but it shouldn't be too hard to add here: https://github.com/ztellman/gloss/blob/master/src/gloss/data/primitives.clj#L122

**Comment by cch1** [comment]
Thanks!  I'm still digesting the protocols in gloss, but I think I'll be able to work it eventually.  For those looking, there is a less-elegant (and unproven) alternative offered here: http://grokbase.com/t/gg/clojure/1514bt3vjg/newbie-gloss-questions-dynamic-buffer-structure
