### ISSUE TITLE
Another decode finite-frame error

### ISSUE THREAD

**Issue by monoid** [clj-commons/gloss#31]
Gloss 0.2.2:

user> (defcodec testinggg (finite-frame 10 :byte))
user/testinggg
user> (gloss.io/decode testinggg (java.nio.ByteBuffer/wrap
                                (.getBytes "0123456789")))
AssertionError Assert failed: (empty? b*)  gloss.data.bytes/wrap-finite-block/fn--9253/fn--9254 (bytes.clj:77)

**Comment by KingMob** [comment]
@monoid @d-t-w 

Flipping the buffer isn't the issue.

The problem is the codec is invalid. The `10` means it should be 10 bytes long, but `:byte` as a frame has only 1. Instead, what should be used is `repeated` with no prefix. The following work:

```clojure
(defcodec testinggg (finite-frame 10 (repeated :byte :prefix :none))) ; with repeated, no prefix
(gloss.io/decode testinggg (java.nio.ByteBuffer/wrap (.getBytes "0123456789")))
=> [48 49 50 51 52 53 54 55 56 57]

(defcodec testinggg (finite-frame 10 :byte)) ; original
(gloss.io/decode testinggg (java.nio.ByteBuffer/wrap (.getBytes "0"))) ; just one byte
=> 48
```
