### ISSUE TITLE
gloss 0.2.5 requires an explicit dependency [byte-streams "0.2.0"] in project.clj

### ISSUE THREAD

**Issue by noncom** [clj-commons/gloss#36]
If you do not specify the dependency in your `project.clj`, both requiring either aleph or gloss will fail with:

`CompilerException java.lang.IllegalAccessError: tuple does not exist, compiling:(byte_streams/graph.clj:1:1)`

I think that gloss is missing the implicit dependency...

**Comment by ztellman** [comment]
It's certainly there: https://github.com/ztellman/gloss/blob/master/project.clj#L7.  If I `lein try gloss 0.2.5`, it also works.  The error you're reporting is due to the transitive dependency on `clj-tuple`, which no longer has a `tuple` function.  Can you give me a full `lein deps :tree`?

**Comment by noncom** [comment]
Sure! I commented out the `[byte-streams "0.2.0"]` and it gives `CompilerException java.lang.IllegalAccessError: tuple does not exist, compiling:(byte_streams/graph.clj:1:1)` on evaling the namespace.

Here is the tree of this setup:

Possibly confusing dependencies found:
[clj-time "0.8.0"] -> [joda-time "2.3"]
 overrides
[selmer "0.7.7"] -> [joda-time "2.4"]

Consider using these exclusions:
[selmer "0.7.7" :exclusions [joda-time]]

[clj-http "1.0.1"] -> [commons-codec "1.9" :exclusions [org.clojure/clojure]]
 overrides
[selmer "0.7.7"] -> [commons-codec "1.10"]

Consider using these exclusions:
[selmer "0.7.7" :exclusions [commons-codec]]

[clj-http "1.0.1"] -> [slingshot "0.10.3" :exclusions [org.clojure/clojure]]
 overrides
[clj-http-lite "0.2.1"] -> [slingshot "0.12.1"]

Consider using these exclusions:
[clj-http-lite "0.2.1" :exclusions [slingshot]]

[me.raynes/conch "0.8.0"] -> [org.flatland/useful "0.10.6"]
 overrides
[lamina "0.5.6"] -> [org.flatland/useful "0.11.1" :exclusions [org.clojure/clojure-contrib org.clojure/contrib]]

Consider using these exclusions:
[lamina "0.5.6" :exclusions [org.flatland/useful]]

[aleph "0.4.0-beta3"] -> [byte-streams "0.2.0-alpha8"]
 overrides
[gloss "0.2.5"] -> [byte-streams "0.2.0"]

Consider using these exclusions:
[gloss "0.2.5" :exclusions [byte-streams]]

[clj-http "1.0.1"] -> [cheshire "5.3.1" :exclusions [org.clojure/clojure]] -> [com.fasterxml.jackson.core/jackson-core "2.3.1"]
 overrides
[clj-http "1.0.1"] -> [com.cognitect/transit-clj "0.8.259" :exclusions [org.clojure/clojure]] -> [com.cognitect/transit-java "0.8.269"] -> [com.fasterxml.jackson.datatype/jackson-datatype-json-org "2.
3.2"] -> [com.fasterxml.jackson.core/jackson-databind "2.3.2"] -> [com.fasterxml.jackson.core/jackson-core "2.3.2"]
 and
[clj-http "1.0.1"] -> [com.cognitect/transit-clj "0.8.259" :exclusions [org.clojure/clojure]] -> [com.cognitect/transit-java "0.8.269"] -> [com.fasterxml.jackson.datatype/jackson-datatype-json-org "2.
3.2"] -> [com.fasterxml.jackson.core/jackson-core "2.3.2"]

Consider using these exclusions:
[clj-http "1.0.1" :exclusions [com.fasterxml.jackson.core/jackson-core]]
[clj-http "1.0.1" :exclusions [com.fasterxml.jackson.core/jackson-core]]

 [aleph "0.4.0-beta3"]
   [byte-streams "0.2.0-alpha8"]
     [primitive-math "0.1.4"]
   [io.aleph/dirigiste "0.1.0-alpha8"]
   [io.netty/netty-all "4.0.25.Final"]
   [org.clojure/tools.logging "0.3.1"]
 [clj-http-lite "0.2.1"]
 [clj-http "1.0.1"]
   [cheshire "5.3.1" :exclusions [[org.clojure/clojure]]]
     [com.fasterxml.jackson.core/jackson-core "2.3.1"]
     [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.3.1"]
     [tigris "0.1.1"]
   [com.cognitect/transit-clj "0.8.259" :exclusions [[org.clojure/clojure]]]
     [com.cognitect/transit-java "0.8.269"]
       [com.fasterxml.jackson.datatype/jackson-datatype-json-org "2.3.2"]
         [com.fasterxml.jackson.core/jackson-databind "2.3.2"]
           [com.fasterxml.jackson.core/jackson-annotations "2.3.0"]
         [org.json/json "20090211"]
       [org.apache.directory.studio/org.apache.commons.codec "1.8"]
       [org.msgpack/msgpack "0.6.10"]
         [com.googlecode.json-simple/json-simple "1.1.1" :exclusions [[junit]]]
         [org.javassist/javassist "3.18.1-GA"]
     [org.clojure/test.check "0.5.9"]
   [commons-codec "1.9" :exclusions [[org.clojure/clojure]]]
   [crouton "0.1.2" :exclusions [[org.clojure/clojure]]]
     [org.jsoup/jsoup "1.7.1"]
   [org.apache.httpcomponents/httpclient "4.3.5" :exclusions [[org.clojure/clojure]]]
     [commons-logging "1.1.3"]
   [org.apache.httpcomponents/httpcore "4.3.3" :exclusions [[org.clojure/clojure]]]
   [org.apache.httpcomponents/httpmime "4.3.5" :exclusions [[org.clojure/clojure]]]
   [org.clojure/tools.reader "0.8.10" :exclusions [[org.clojure/clojure]]]
   [slingshot "0.10.3" :exclusions [[org.clojure/clojure]]]
 [clj-time "0.8.0"]
   [joda-time "2.3"]
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [com.dropbox.core/dropbox-core-sdk "1.7.7" :exclusions [[com.fasterxml.jackson.core/jackson-core]]]
 [com.googlecode.juniversalchardet/juniversalchardet "1.0.3"]
 [com.novemberain/monger "2.0.0"]
   [clojurewerkz/support "0.20.0"]
     [com.google.guava/guava "14.0.1"]
   [org.mongodb/mongo-java-driver "2.12.1"]
 [commons-io "2.4"]
 [ddf.minim "2.2.0"]
   [org.clojars.automata/jl "1.0.0"]
   [org.clojars.automata/mp3spi "1.9.4"]
   [org.clojars.automata/tritonus-aos "1.0.0"]
   [org.clojars.automata/tritonus-share "1.0.0"]
 [edn-validator "0.2.0-20140518.003038-1"]
   [instaparse "1.3.2"]
 [environ "1.0.0"]
 [gloss "0.2.5"]
 [lamina "0.5.6"]
 [manifold "0.1.0"]
   [riddley "0.1.9"]
 [me.raynes/conch "0.8.0"]
   [org.flatland/useful "0.10.6"]
     [org.clojure/tools.macro "0.1.1"]
 [org.clojure/clojure "1.7.0-beta1"]
 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
   [org.clojure/tools.analyzer.jvm "0.1.0-beta12"]
     [org.clojure/core.memoize "0.5.6"]
       [org.clojure/core.cache "0.6.3"]
         [org.clojure/data.priority-map "0.0.2"]
     [org.clojure/tools.analyzer "0.1.0-beta12"]
     [org.ow2.asm/asm-all "4.1"]
 [org.clojure/data.xml "0.0.8"]
 [org.clojure/tools.nrepl "0.2.6" :scope "test" :exclusions [[org.clojure/clojure]]]
 [potemkin "0.3.13"]
   [clj-tuple "0.2.1"]
 [selmer "0.7.7"]

**Comment by csdrane** [comment]
I'm receiving a similar error while using `lein try`:

```CompilerException java.lang.IllegalAccessError: vector does not exist, compiling:(byte_streams/graph.clj:1:1)```

**Comment by shofetim** [comment]
@csdrane Did you find a solution? I have the same error.

**Comment by csdrane** [comment]
No but I didn't pursue it further. Good luck!

**Comment by shofetim** [comment]
Looks like it was conflicts with other dependencies, once I added some exclusions everything worked well.

**Comment by ztellman** [comment]
Sorry, lost track of this.  If you explicitly specify `clj-tuple` 0.2.2, it should fix things.
