### ISSUE TITLE
Documentation link

### ISSUE THREAD

**Issue by mcarpenter** [clj-commons/gloss#58]
Hi,

Two small issues:

1. The current README [link](https://cljdoc.org/d/org.clj-commons/gloss) to the API docs at cljdocs.org is broken ("Could not find release for org.clj-commons/gloss").

2. I found [version 0.2.6](https://cljdoc.org/d/gloss/gloss/0.2.6/doc/readme) on cljdocs but it would be nice to read the latest and greatest if possible.

Thanks

**Comment by KingMob** [comment]
Thanks, @mcarpenter . We're straightening out a failure with deployment after switching to clj-commons. The way cljdoc works, the automatic version/doc detection requires the code be pushed up _before_ you deploy, so the README is more up-to-date than the artifacts at the moment. Once deployment's fixed, everything should line up correctly.

**Comment by KingMob** [comment]
The clj-commons CI person said they'd be able to fix the deployment permissions next week, so check back then.

**Comment by KingMob** [comment]
@mcarpenter Just checked back, and this is fixed. Unfortunately, the badges have some known caching issues, but they do link to the most recent versions on clojars.
